"""Orchestration: raw HTTP text in, pcap bytes out."""

from raw2pcap.config import DEFAULT_MSS
from raw2pcap.parser import parse_request, parse_response
from raw2pcap.selfcheck import verify_pcap
from raw2pcap.synth import (
    DEFAULT_CLIENT_IP,
    DEFAULT_SERVER_IP,
    build_session,
)

_DUMMY_REQUEST = (
    "GET / HTTP/1.1\r\n"
    "Host: example.com\r\n"
    "User-Agent: Mozilla/5.0\r\n"
    "Accept: */*\r\n"
    "Connection: close\r\n"
    "\r\n"
)

_DUMMY_RESPONSE = "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\ngenerated by raw2pcap"


def generate_pcap(
    raw_request: str | None = None,
    raw_response: str | None = None,
    *,
    client_ip: str = DEFAULT_CLIENT_IP,
    server_ip: str = DEFAULT_SERVER_IP,
    client_port: int = 50000,
    base_time: float | None = None,
) -> bytes:
    """Generate pcap bytes from raw HTTP request and/or response text.

    When only one side is given, the other side is synthesized (a dummy GET
    request, or a canned 200 response with body "generated by raw2pcap") so
    the capture still shows a plausible exchange. The server port is taken
    from the request's Host header (default 80).
    """
    has_request = bool(raw_request and raw_request.strip())
    has_response = bool(raw_response and raw_response.strip())
    if not has_request and not has_response:
        raise ValueError("at least one of raw_request/raw_response must be provided")

    request_bytes = None
    server_port = 80
    if has_request:
        request = parse_request(raw_request)
        server_port = request.host_port()
        request_bytes = request.to_bytes()

    response_bytes = None
    if has_response:
        response_bytes = parse_response(raw_response).to_bytes()

    if request_bytes is None:
        request_bytes = parse_request(_DUMMY_REQUEST).to_bytes()
    if response_bytes is None:
        # Always show a complete exchange: fall back to a canned 200 response.
        response_bytes = parse_response(_DUMMY_RESPONSE).to_bytes()

    pcap = build_session(
        request=request_bytes,
        response=response_bytes,
        client_ip=client_ip,
        server_ip=server_ip,
        client_port=client_port,
        server_port=server_port,
        base_time=base_time,
        mss=DEFAULT_MSS,
    )
    # Round-trip self-check: re-dissect what we just wrote and assert the
    # payloads on the wire byte-match the HTTP messages we were given.
    verify_pcap(
        pcap,
        client_ip=client_ip,
        server_ip=server_ip,
        client_port=client_port,
        server_port=server_port,
        client_payload=request_bytes,
        server_payload=response_bytes,
    )
    return pcap
