from io import BytesIO

from fastapi.testclient import TestClient
from scapy.layers.inet import IP, TCP
from scapy.utils import rdpcap

from raw2pcap.api import app

client = TestClient(app)

REQUEST = "GET /hello HTTP/1.1\r\nHost: example.com\r\n\r\n"
RESPONSE = "HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nworld"


def test_index_serves_form():
    resp = client.get("/")
    assert resp.status_code == 200
    assert "inputRequest" in resp.text
    assert "inputResponse" in resp.text


def test_favicon_served():
    resp = client.get("/static/favicon.svg")
    assert resp.status_code == 200
    assert resp.headers["content-type"].startswith("image/svg+xml")
    assert b"r2p" in resp.content


def test_create_pcap_from_request_and_response():
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": RESPONSE},
    )
    assert resp.status_code == 200
    assert resp.content[:4] == b"\xd4\xc3\xb2\xa1"
    assert "attachment" in resp.headers["content-disposition"]


def test_create_pcap_request_required():
    resp = client.post("/api/pcap", data={"inputRequest": "", "inputResponse": RESPONSE})
    assert resp.status_code == 400
    assert any("request is required" in m for m in resp.json()["detail"])


def test_filename_reflected_in_content_disposition():
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "filename": "my-capture"},
    )
    assert resp.headers["content-disposition"] == 'attachment; filename="my-capture.pcap"'


def test_filename_sanitized():
    resp = client.post(
        "/api/pcap",
        data={
            "inputRequest": REQUEST,
            "inputResponse": "",
            "filename": 'a/b\\c:d*e?f"g<h>i|j',
        },
    )
    assert resp.headers["content-disposition"] == 'attachment; filename="abcdefghij.pcap"'


def test_filename_default_when_blank():
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "filename": "  "},
    )
    assert resp.headers["content-disposition"] == 'attachment; filename="raw2pcap-result.pcap"'


def test_filename_newline_stripped_from_header():
    # A raw newline must never reach Content-Disposition: it could split the
    # header or break stricter HTTP stacks that reject it outright.
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "filename": "evil\nX-Injected: 1"},
    )
    assert resp.status_code == 200
    cd = resp.headers["content-disposition"]
    assert "\n" not in cd and "\r" not in cd


def test_filename_cjk_uses_rfc5987():
    # Non-ASCII names cannot travel in a latin-1 header verbatim; they go
    # percent-encoded in filename* with an ASCII fallback in filename=.
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "filename": "捕获文件"},
    )
    assert resp.status_code == 200
    cd = resp.headers["content-disposition"]
    assert 'attachment; filename="raw2pcap-result.pcap"' in cd
    assert "filename*=UTF-8''%E6%8D%95%E8%8E%B7%E6%96%87%E4%BB%B6.pcap" in cd


def test_filename_mixed_ascii_and_cjk_keeps_ascii_fallback():
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "filename": "捕获demo"},
    )
    assert resp.status_code == 200
    cd = resp.headers["content-disposition"]
    assert 'attachment; filename="demo.pcap"' in cd
    assert "filename*=UTF-8''%E6%8D%95%E8%8E%B7demo.pcap" in cd


def test_create_pcap_request_only_gets_canned_response():
    resp = client.post("/api/pcap", data={"inputRequest": REQUEST, "inputResponse": ""})
    assert resp.status_code == 200
    assert b"generated by raw2pcap" in resp.content


def test_create_pcap_empty_input_rejected():
    resp = client.post("/api/pcap", data={"inputRequest": "", "inputResponse": ""})
    assert resp.status_code == 400


def test_create_pcap_garbage_rejected():
    resp = client.post("/api/pcap", data={"inputRequest": "not http", "inputResponse": ""})
    assert resp.status_code == 400


def test_create_pcap_missing_host_rejected():
    bad = "GET / HTTP/1.1\r\nAccept: */*\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": bad, "inputResponse": ""})
    assert resp.status_code == 400
    assert any("Host" in m for m in resp.json()["detail"])


def test_create_pcap_whitespace_separator_rejected():
    bad = "POST / HTTP/1.1\r\nHost: example.com\r\n \r\nbody"
    resp = client.post("/api/pcap", data={"inputRequest": bad, "inputResponse": ""})
    assert resp.status_code == 400


def test_create_pcap_warnings_in_header():
    bad_cl = "HTTP/1.1 200 OK\r\nContent-Length: 99\r\n\r\nshort"
    resp = client.post("/api/pcap", data={"inputRequest": REQUEST, "inputResponse": bad_cl})
    assert resp.status_code == 200
    warnings = resp.headers["x-raw2pcap-warnings"]
    assert "Content-Length" in warnings


def test_oversized_content_length_rejected():
    body = "A" * (300 * 1024)
    resp = client.post("/api/pcap", data={"inputRequest": body, "inputResponse": ""})
    assert resp.status_code == 413


def test_oversized_chunked_body_rejected():
    # No Content-Length: the endpoint-level check must catch it instead.
    big = "POST / HTTP/1.1\r\nHost: example.com\r\n\r\n" + "A" * (300 * 1024)
    resp = client.post(
        "/api/pcap",
        content=f"inputRequest={big}",
        headers={
            "content-type": "application/x-www-form-urlencoded",
            "transfer-encoding": "chunked",
        },
    )
    assert resp.status_code == 413


def test_host_port_out_of_range_returns_clean_400():
    bad = "GET / HTTP/1.1\r\nHost: example.com:99999\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": bad, "inputResponse": ""})
    assert resp.status_code == 400
    detail = " ".join(resp.json()["detail"])
    assert "port" in detail.lower()
    assert "scapy" not in detail.lower()


def test_duplicate_content_length_rejected():
    bad = "HTTP/1.1 200 OK\r\nContent-Length: 5\r\nContent-Length: 0\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": REQUEST, "inputResponse": bad})
    assert resp.status_code == 400
    assert any("multiple Content-Length" in m for m in resp.json()["detail"])


def test_size_check_counts_bytes_not_characters():
    from raw2pcap import api

    # "é" is 2 bytes in UTF-8: 5 characters but 10 bytes.
    assert api._utf8_bytes("é" * 5) == 10


def test_oversized_multibyte_body_rejected():
    # 90k CJK characters are only 90k "characters" but 270 KB of UTF-8 bytes,
    # above the 256 KiB limit. Sent chunked so only the endpoint-level byte
    # check can catch it.
    big = "汉" * (90 * 1024)
    resp = client.post(
        "/api/pcap",
        content=f"inputRequest={big}",
        headers={
            "content-type": "application/x-www-form-urlencoded",
            "transfer-encoding": "chunked",
        },
    )
    assert resp.status_code == 413


def test_custom_ips_used_in_pcap():
    resp = client.post(
        "/api/pcap",
        data={
            "inputRequest": REQUEST,
            "inputResponse": "",
            "clientIp": "127.0.0.2",
            "serverIp": "192.168.1.10",
        },
    )
    assert resp.status_code == 200
    pkts = rdpcap(BytesIO(resp.content))
    assert pkts[0][IP].src == "127.0.0.2"
    assert pkts[0][IP].dst == "192.168.1.10"


def test_empty_ip_fields_use_defaults():
    resp = client.post(
        "/api/pcap",
        data={
            "inputRequest": REQUEST,
            "inputResponse": "",
            "clientIp": "",
            "serverIp": "",
        },
    )
    assert resp.status_code == 200
    pkts = rdpcap(BytesIO(resp.content))
    assert pkts[0][IP].src == "10.0.0.1"
    assert pkts[0][IP].dst == "10.0.0.2"


def test_invalid_client_ip_rejected():
    resp = client.post(
        "/api/pcap",
        data={"inputRequest": REQUEST, "inputResponse": "", "clientIp": "999.1.1.1"},
    )
    assert resp.status_code == 400
    assert any("IPv4" in m for m in resp.json()["detail"])


def test_server_ip_derived_from_host():
    raw = "GET / HTTP/1.1\r\nHost: 36.4.1.8:7001\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": raw, "inputResponse": ""})
    assert resp.status_code == 200
    pkts = rdpcap(BytesIO(resp.content))
    assert pkts[0][IP].src == "10.0.0.1"
    assert pkts[0][IP].dst == "36.4.1.8"


def test_host_127_0_0_1_keeps_default_dst():
    raw = "GET / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": raw, "inputResponse": ""})
    assert resp.status_code == 200
    pkts = rdpcap(BytesIO(resp.content))
    assert pkts[0][IP].dst == "10.0.0.2"


def test_bare_ipv6_host_rejected():
    # RFC 7230: IPv6 literals must be bracketed. Bare "::1" used to slip
    # through and silently synthesize a session to destination port 1.
    raw = "GET / HTTP/1.1\r\nHost: ::1\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": raw, "inputResponse": ""})
    assert resp.status_code == 400
    detail = " ".join(resp.json()["detail"])
    assert "bracket" in detail.lower()


def test_bracketed_ipv6_host_accepted():
    raw = "GET / HTTP/1.1\r\nHost: [::1]:8080\r\n\r\n"
    resp = client.post("/api/pcap", data={"inputRequest": raw, "inputResponse": ""})
    assert resp.status_code == 200
    pkts = rdpcap(BytesIO(resp.content))
    assert pkts[0][IP].dst == "10.0.0.2"  # IPv6 hosts fall back to the default
    assert pkts[0][TCP].dport == 8080  # port after "]" is honored


def test_create_pcap_with_file_uploads():
    resp = client.post(
        "/api/pcap",
        files={
            "inputRequest": ("request.txt", REQUEST.encode("utf-8")),
            "inputResponse": ("response.txt", RESPONSE.encode("utf-8")),
        },
    )
    assert resp.status_code == 200
    assert resp.content[:4] == b"\xd4\xc3\xb2\xa1"


def test_create_pcap_file_upload_request_only():
    resp = client.post(
        "/api/pcap",
        files={"inputRequest": ("request.txt", REQUEST.encode("utf-8"))},
    )
    assert resp.status_code == 200


def test_create_pcap_binary_upload_rejected():
    resp = client.post(
        "/api/pcap",
        files={"inputRequest": ("request.txt", b"\xff\xfe\x00 binary")},
    )
    assert resp.status_code == 400
    assert any("UTF-8" in m for m in resp.json()["detail"])
